---
title: '<span style="display:none">Committee</span>'
author: '<span style="display:none">Karen Cristine Goncalves dos Santos</span>'
name: "Committee"
output: 
  html_document
---
<head>
<link rel="alternate" hreflang="fr-fr" href="../fr/participer.html">
<link rel="stylesheet" href="committe_style.css">

```{r echo=FALSE, results='asis'}
source('header.R')
```
<br><br>

<div class="col-md-3" style="float:right">

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
source("sidebar.R", local = knitr::knit_global())

```

</div>

<section class="col-md-9" id="col9" style="padding-right: 2%; float: left;">
<div class="row text" id="row_text_col9">

<div  id="section-1" class="section level1 tabset tabset-fade tabset-pills">
<h1></h1>

<div id="Role_description" class="section level2">
<h2> Description of the roles</h2>


```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/description_functions.R', 
       local = knitr::knit_global())
```


</div><!-- id="Role_description" -->

<div id="Current" class="section level2">
<h2> Current</h2>

```{r Committee 2023, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/table_2023.R', 
       local = knitr::knit_global())
```
</div>

<div id="Past" class="section level2 tabset tabset-fade tabset-pills">
<h2> Past </h2>

### 2022

```{r  Committee 2022, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/table_2022.R', 
       local = knitr::knit_global())
```



### 2021

```{r  Committee 2021, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/table_2021.R', 
       local = knitr::knit_global())
```


<div id="comite_2020" class="section level3 tabset tabset-fade tabset-pills">
<h3> 2020 </h3>

#### 2020-05

```{r  Committee 2020-05, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/table_2020-05.R', 
       local = knitr::knit_global())
```

<br><br>

#### 2020-01-10

```{r  Committee 2020-01, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/table_2020-01.R', 
       local = knitr::knit_global())
```

</div><!-- id="comite_2020" -->

###  2019

```{r Committee 2019, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
options(encoding = "utf-8", Encoding = "utf-8")
source('committee_scripts/table_2019.R', 
       local = knitr::knit_global())
```

</div><!-- closing div Past-->
</div><!-- closing div id=section-1-->
</div><!-- closing div id="row_text_col9"-->

</div><!-- closing div id=col9 -->


</div><!-- closing div class row under container-fluid div -->
</div><!-- closing container-fluid -->


```{r Links, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
source('committee_scripts/links.R', 
       local = knitr::knit_global())
```
