cat(paste('<details>',
					'<summary><a class="sidebar_links_list" href="news_2023.html#2023">2023</a></summary>',
					'<ul>',
					'<li><a class="sidebar_links_list" href="news_2023.html#2023-06-01">Morocco summer school</a></li>',
					'<li><a class="sidebar_links_list" href="news_2023.html#2023-04-07">New CPICS members - full committee</a></li>',
					'<li><a class="sidebar_links_list" href="news_2023.html#2023-02-23">New CPICS members</a></li>',
					'</ul>',
					'</details>','<details>',
					'<summary><a class="sidebar_links_list" href="news_2022.html#2022">2022</a></summary>',
					'<ul>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-11-17">Journ&eacute;es du Centre S&Egrave;VE 2022</a></li>',		
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-10-06">Forces AVENIR - Claire Letanneur</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-09-07">Publication of the new PhD, Andrew Diamond</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-09-05">Centre S&Egrave;VE\'s students\' new beginnings</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-08-31">Publication Molecules - Isabel Desgagn&eacute;-Penix</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-07-25">Publication Biomolecules - Isabel Desgagn&eacute;-Penix</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-04-07">Collaboration Italy and Isabel Desgagn&eacute;-Penix\'s lab</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-05-04">Romaric Mouafo new postdoc</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-04-26">20 years of GRBV</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-04-12">Germain\'s group in India</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-03-10">Amal Jaballi\'s  and Charles Roussin-L&eacute;veill&eacute;e\'s publications</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-02-10">Marianne Bessette\'s publications</a></li>',
					'<li><a class="sidebar_links_list" href="news_2022.html#2022-01-03">Isabel Desgagn&eacute;-Penix\'s publications</a></li>',
					'</details>','<details>',
					'<summary><a class="sidebar_links_list" href="news_2021.html#2021">2021</a></summary>',
					'<ul>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-12-03">Julie Yergeau\'s award</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-11-24">Finished PhD - Romaric Moaufo</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-09-02">Isabel Desgagn&eacute;-Penix\'s publication</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-08-30">Karen Goncalves\'s interview</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-05-05">Karen Goncalves\'s publication</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-04-06">Publications from Centre S&Egrave;VE professors</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-01-29">CPICS new members</a></li>',
					'<li><a class="sidebar_links_list" href="news_2021.html#2021-01-27">Michelle Boivin\'s project</a></li>',
					'</details>','<details>',
					'<summary><a class="sidebar_links_list" href="news_2020.html#2020">2020</a></summary>',
					'<ul>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-11-06">Maribel Diaz\'s publication</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-11-10">Synbio Canada Webinar</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-11-06">Karen Goncalves\'s pre-print</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-11-05">Fadoua Dhaouadi\'s publication</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-10-27">Romaric Maouafo\'s MT180 finals</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-10-24">Hugo Germain\'s and Isabel Desgagn&eacute;-Penix\'s labs award</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-10-02">Centre S&Egrave;VE poster 2020 competition</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-09-22">Web Conference Centre S&Egrave;VE - L&eacute;veill&eacute;e</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-08-17">Isabelle Laforest-Lapoint\'s research</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-08-14">Leena Tripathi\'s research</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-08-10">Web Conferences Centre S&Egrave;VE</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-07-29">Worldwide Plant Biology Summit</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-07-07">Web Conference Centre S&Egrave;VE - Fatima Awwad</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-06-16">Web Conference Centre S&Egrave;VE - Karen Goncalves</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-05-09">New secretaries of the CPICS</a></li>',
					'<li><a class="sidebar_links_list" href="news_2020.html#2020-03-02">FRQNT funding for Claire Letaneur</a></li>',
					'</details>','<details>',
					'<summary><a class="sidebar_links_list" href="news_2019.html#2019">2019</a></summary>',
					'<ul>',
					'<li><a class="sidebar_links_list" href="news_2019.html#2019-09-30">Rose-Marie Bell\'s post</a></li>',
					'<li><a class="sidebar_links_list" href="news_2019.html#2019-08-29">Memories of the CPICS Symposium</a></li>',
					'<li><a class="sidebar_links_list" href="news_2019.html#2019-06-11">Registrations for the CPICS Symposium</a></li>',
					'<li><a class="sidebar_links_list" href="news_2019.html#2019-03-14">Introduction of the CPICS</a></li>',
					'</ul>',
					'</details>',
					sep = "\n"
))