---
title: '<span style="display:none">Get involved</span>'
author: '<span style="display:none">Karen Cristine Goncalves dos Santos</span>'
output: 
  html_document
---

<head>
<link rel="alternate" hreflang="fr-fr" href="../fr/participer.html">
<link rel="stylesheet" href="form.css">

```{r echo=FALSE, results='asis'}
source('header.R')
```

<section class="col-md-9" style="padding-right:2%"><!--December 2020-->
<div class="row text">

<form name="CPICS_participation" method="POST" data-netlify="true">
<fieldset aria-required="true">
By filling out this form, you accept to receive invitation emails to the next CPICS meetings.

</fieldset>

<!-- ARE you a CS member
<div class="form-row">
<fieldset aria-required="true">
Only fill out this form if you are a student/postdoctorate fellow member of Centre SEVE.<br>

If you don't know if you are a member, search for your professor <a href="https://centreseve.recherche.usherbrooke.ca/en/researchers">here</a>


</fieldset>
</div> -->

<!-- Name -->
<div class="form-row">
<fieldset aria-required="true">
<legend>Name</legend>
<label for="firstName">First name</label><input type="text" name="firstName" id="firstName" aria-required="true" data-ok="false" required/> <span class="error-msg" id="firstNameErr"></span>
</div>
<div class="form-row">
<label for="lastName">Last name</label><input type="text" name="lastName" id="lastName" aria-required="true" data-ok="false" required/> <span class="error-msg" id="lastNameErr"></span>
</fieldset>
</div>
<br>
<!-- University -->
<div class="form-row">
<fieldset aria-required="true">
<legend>Your lab</legend>
<label for="University">University</label><input type="text" name="University" id="University" aria-required="true" data-ok="false" required/> <span class="error-msg" id="UniversityErr"></span>
<label for="Supervisor">Name of your supervisor</label> <input type="text" name="Supervisor" id="Supervisor" aria-required="true" data-ok="false" required/>
</fieldset>
</div>
<br>

<!-- Email -->
<div class="form-row">
<fieldset aria-required="true">
<legend>E-mail</legend>
<input type="text" name="email" id="email" aria-required="true" data-ok="false" required/> <span class="error-msg" id="emailErr"></span>
</fieldset>
</div>
<br>

<!-- Status -->
<div class="form-row">
<fieldset aria-required="true">
<center><legend>Your status</legend>
<input type="radio" id="masters" name="status" required="required" value="Master's student">
<label for="masters">Master's student</label>
<input type="radio" id="phd" name="status" required="required" value="Ph.D. student">
<label for="phd">Ph.D. student</label>
<input type="radio" id="postdoc" name="status" required="required" value="Postdoctorate fellow">
<label for="postdoc">Postdoctorate fellow</label></center>
</fieldset>
</div>
<br>

<center> <button type="submit" class="btn" aria-disabled="true" aria-describedby="CSmemberErr"> Submit </button></center>
</form>

</div>
</section> 

<section class="col-md-3">

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
source("sidebar.R", local = knitr::knit_global())

```
</section> 

<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
source("topFunctionJS.R", local = knitr::knit_global())

```
</div>
</main>
