cat(paste('<ul>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022">2022</a></li>',
      '<ul>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-09-07">Publication du nouveau docteur, Andrew Diamond</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-09-05">Des nouveaux débuts pour des étudiants du Centre SÈVE\'s students</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-08-31">Molecules - Dre Isabel Desgagn&eacute;-Penix</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-07-25">Biomolecules - Dre Isabel Desgagn&eacute;-Penix</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-04-07">Collaboration Italie - Dre Isabel Desgagn&eacute;-Penix</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-05-04">Nouveau postdoctorat de Romaric Mouafo</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-04-26">20 ans de GRBV</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-04-12">Groupe du Dr. Germain en Inde</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-03-10">Publications de Amal Jaballi et Charles Roussin-Leveillee</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-02-10">Publication de Marianne Bessette</a></li>',
      '<li><a class="sidebar_links_list" href="news_2022.html#2022-01-03">Publication de la Dre Isabel Desgagn&eacute;-Penix</a></li>',
      '</ul>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021">2021</a></li>',
      '<ul>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-12-03">Prix de Julie Yergeau</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-11-24">Fin de doctorat - Romaric Moaufo</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-09-02">Publication de Dre la Isabel Desgagn&eacute;-Penix</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-08-30">Interview de la Dre Karen Goncalves</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-05-05">Publication de la Dre Karen Goncalves</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-04-06">Publications des professeurs du Centre S&Egrave;VE</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-01-29">Nouveaux membres du CPICS</a></li>',
      '<li><a class="sidebar_links_list" href="news_2021.html#2021-01-27">Projet de Michelle Boivin</a></li>',
      '</ul>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020">2020</a></li>',
      '<ul>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-11-06">Publication de Maribel Diaz</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-11-10">Webinar de Synbio Canada</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-11-06">Pre-print de Karen Goncalves</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-11-05">Publication de Fadoua Dhaouadi</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-10-27">Finale MT180 - Romaric Maouafo</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-10-24">Prix des labs de Dr. Germain et Dre. Desgagn&eacute;-Penix</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-10-02">Concours d\'affiches Centre S&Egrave;VE</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-09-22">Conf&eacute;rence Web Centre S&Egrave;VE - Charles Roussin-L&eacute;veill&eacute;e</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-08-17">Recherche de la Dre Isabelle Laforest-Lapoint</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-08-14">Recherche de la Dre Leena Tripathi</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-08-10">Conf&eacute;rence Web Centre S&Egrave;VE</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-07-29">Worldwide Plant Biology Summit</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-07-07">Conf&eacute;rence Web Centre S&Egrave;VE - Fatima Awwad</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-06-16">Conf&eacute;rence Web Centre S&Egrave;VE - Karen Goncalves</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-05-09">Nouveaux secr&eacute;taires du CPICS</a></li>',
      '<li><a class="sidebar_links_list" href="news_2020.html#2020-03-02">Financement FRQNT &agrave; Claire Letaneur</a></li>',
      '</ul>',
      '<li><a class="sidebar_links_list" href="news_2019.html#2019">2019</a></li>',
      '<ul>',
      '<li><a class="sidebar_links_list" href="news_2019.html#2019-09-30">Article de Rose-Marie Bell</a></li>',
      '<li><a class="sidebar_links_list" href="news_2019.html#2019-08-29">Memoires du Symposium du CPICS</a></li>',
      '<li><a class="sidebar_links_list" href="news_2019.html#2019-06-11">Inscriptions au Symposium du CPICS</a></li>',
      '<li><a class="sidebar_links_list" href="news_2019.html#2019-03-14">Introduction du CPICS</a></li>',
      '</ul>',
      '</ul>', sep = "\n"
))